name: Refresh Pagespeed results for README
on:
  schedule:
    - cron: "5 0 * * tue" # Every tuesday at 00:05 UTC
  workflow_dispatch:

jobs:
  getpsresults:
    env:
      PSURL: https://pagespeed-insights-svg.glitch.me
      HOST: https://rockraiders.rocks
      RESULTSFOLDER: .github/.lighthouse/
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Fetch resulsts and save it in the repo
      run: |
          mkdir -p ${RESULTSFOLDER}
          curl "${PSURL}/?url=${HOST}&strategy=desktop" > ./${RESULTSFOLDER}/PSIRD.svg
          curl "${PSURL}/?url=${HOST}&strategy=mobile" > ./${RESULTSFOLDER}/PSIRM.svg
    - name: Commit files
      run: |
        git add .
        git config --local user.email "actions@github.com"
        git config --local user.name "github-actions[bot]"
        git diff --quiet && git diff --staged --quiet || git commit -am "Updated Pagespeed results"
        git push
